<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Neros.Application\Neros.Application.csproj" />
    <ProjectReference Include="..\Neros.Contracts\Neros.Contracts.csproj" />
    <ProjectReference Include="..\Neros.Shared\Neros.Shared.csproj" />
  </ItemGroup>

</Project>
