<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>neros-api-desarrollo</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\src\BuildingBlocks\Neros.ServiceDefaults\Neros.ServiceDefaults.csproj" />
    <ProjectReference Include="..\Neros.Application\Neros.Application.csproj" />
    <ProjectReference Include="..\Neros.Persistence\Neros.Persistence.csproj" />
    <ProjectReference Include="..\src\Services\Organization\Neros.Organization.Persistence\Neros.Organization.Persistence.csproj" />
    <ProjectReference Include="..\Neros.Contracts\Neros.Contracts.csproj" />
    <ProjectReference Include="..\Neros.Shared\Neros.Shared.csproj" />
  </ItemGroup>

</Project>
