<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\Neros.ServiceDefaults\Neros.ServiceDefaults.csproj" />
    <ProjectReference Include="..\Neros.Terceros.Persistence\Neros.Terceros.Persistence.csproj" />
  </ItemGroup>
</Project>
